# Generated by Django 5.2.18 on 2026-10-08 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecte', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='collecté sur les parts')),
                ('commission', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='commission')),
                ('verse', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='versé au groupeur')),
                ('frais_livraison_collectes', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='frais de livraison collectés')),
                ('effectue_le', models.DateTimeField(auto_now_add=True, verbose_name='effectué le')),
                ('campagne', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='versement', to='catalogue.campagne', verbose_name='campagne')),
            ],
            options={
                'verbose_name': 'versement',
                'verbose_name_plural': 'versements',
                'ordering': ('-effectue_le',),
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('variante', models.CharField(blank=True, max_length=60, verbose_name='variante')),
                ('montant_parts', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant des parts')),
                ('frais_livraison', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='frais de livraison')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='total payé')),
                ('quartier', models.CharField(max_length=40, verbose_name='quartier')),
                ('repere', models.CharField(max_length=200, verbose_name='repère')),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone à joindre')),
                ('code_livraison', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='code de livraison')),
                ('cle_idempotence', models.CharField(db_index=True, max_length=80, unique=True, verbose_name="clé d'idempotence")),
                ('statut', models.CharField(choices=[('payee', 'Payée — en attente de clôture'), ('cloturee', 'Groupage clôturé'), ('chez-le-groupeur', 'Commande en cours chez le groupeur'), ('en-livraison', 'En cours de livraison'), ('livree', 'Livrée'), ('litige', 'Litige'), ('remboursee', 'Remboursée'), ('annulee', 'Groupage annulé')], default='payee', max_length=20, verbose_name='statut')),
                ('passee_le', models.DateTimeField(auto_now_add=True, verbose_name='passée le')),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='comptes.acheteur', verbose_name='acheteur')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='catalogue.campagne', verbose_name='campagne')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'ordering': ('-passee_le',),
                'indexes': [models.Index(fields=['campagne', 'statut'], name='commandes_c_campagn_986c7a_idx')],
            },
        ),
    ]
