# Generated by Django 5.2.18 on 2026-10-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_campagne_caracteristiques_campagne_point_remise_and_more'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='etat',
            field=models.CharField(choices=[('en-attente', 'En attente du devis'), ('effectue', 'Effectué'), ('annule', 'Annulé')], default='en-attente', max_length=20, verbose_name='état'),
        ),
        migrations.AddField(
            model_name='versement',
            name='libere_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='libéré le'),
        ),
        migrations.AddField(
            model_name='versement',
            name='libere_par',
            field=models.CharField(blank=True, max_length=120, verbose_name='libéré par'),
        ),
        migrations.AlterField(
            model_name='versement',
            name='effectue_le',
            field=models.DateTimeField(auto_now_add=True, verbose_name='calculé le'),
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('devis', 'Devis fournisseur'), ('recu', 'Reçu de paiement')], max_length=10, verbose_name='nature')),
                ('fournisseur', models.CharField(max_length=160, verbose_name='fournisseur')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='montant')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='référence de stockage')),
                ('etat', models.CharField(choices=[('en-attente', 'À contrôler'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en-attente', max_length=20, verbose_name='état')),
                ('motif_refus', models.CharField(blank=True, max_length=240, verbose_name='motif du refus')),
                ('depose_le', models.DateTimeField(auto_now_add=True, verbose_name='déposé le')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='catalogue.campagne', verbose_name='campagne')),
            ],
            options={
                'verbose_name': 'justificatif',
                'verbose_name_plural': 'justificatifs',
                'ordering': ('-depose_le',),
                'constraints': [models.UniqueConstraint(fields=('campagne', 'nature'), name='un_justificatif_par_nature')],
            },
        ),
    ]
