# Generated by Django 5.2.18 on 2026-10-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=160, verbose_name='produit')),
                ('quantite', models.CharField(max_length=60, verbose_name='quantité')),
                ('quartier', models.CharField(max_length=40, verbose_name='quartier')),
                ('budget_maximum', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='budget maximum')),
                ('precisions', models.TextField(blank=True, verbose_name='précisions')),
                ('statut', models.CharField(choices=[('en-attente', 'En attente'), ('prise-en-charge', 'Prise en charge'), ('campagne-lancee', 'Groupage lancé'), ('non-aboutie', 'Non aboutie')], default='en-attente', max_length=20, verbose_name='statut')),
                ('deposee_le', models.DateTimeField(auto_now_add=True, verbose_name='déposée le')),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='comptes.acheteur', verbose_name='acheteur')),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_satisfaites', to='catalogue.campagne', verbose_name='campagne lancée')),
            ],
            options={
                'verbose_name': 'demande',
                'verbose_name_plural': 'demandes',
                'ordering': ('-deposee_le',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='question')),
                ('etat', models.CharField(choices=[('publiee', 'Publiée'), ('en-verification', 'En vérification'), ('refusee', 'Refusée')], default='publiee', max_length=20, verbose_name='état')),
                ('posee_le', models.DateTimeField(auto_now_add=True, verbose_name='posée le')),
                ('reponse', models.TextField(blank=True, verbose_name='réponse')),
                ('repondue_le', models.DateTimeField(blank=True, null=True, verbose_name='répondue le')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='comptes.acheteur', verbose_name='auteur')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalogue.campagne', verbose_name='campagne')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ('-posee_le',),
            },
        ),
    ]
