# Generated by Django 5.2.18 on 2026-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='téléphone')),
                ('nom', models.CharField(blank=True, max_length=120, verbose_name='nom')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'acheteur',
                'verbose_name_plural': 'acheteurs',
                'ordering': ('-cree_le',),
            },
        ),
        migrations.CreateModel(
            name='Groupeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonyme', models.CharField(max_length=60, unique=True, verbose_name='pseudonyme')),
                ('nom_complet', models.CharField(max_length=120, verbose_name='nom complet')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='téléphone')),
                ('niveau', models.CharField(choices=[('entree', 'Entrée'), ('confirme', 'Confirmé'), ('etabli', 'Établi')], default='entree', max_length=20, verbose_name='niveau de vérification')),
                ('statut_kyc', models.CharField(choices=[('a-completer', 'À compléter'), ('en-verification', 'En vérification'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='a-completer', max_length=20, verbose_name='statut du dossier')),
                ('titulaire_mobile_money', models.CharField(blank=True, max_length=120, verbose_name='titulaire du compte Mobile Money')),
                ('numero_mobile_money', models.CharField(blank=True, max_length=20, verbose_name='numéro Mobile Money')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'groupeur',
                'verbose_name_plural': 'groupeurs',
                'ordering': ('pseudonyme',),
            },
        ),
    ]
