# Generated by Django 5.2.18 on 2026-10-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeur',
            name='courriel',
            field=models.EmailField(blank=True, max_length=254, verbose_name='courriel'),
        ),
        migrations.CreateModel(
            name='DecisionKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('valide', 'Validé'), ('a-completer', 'À compléter'), ('refuse', 'Refusé')], max_length=20, verbose_name='issue')),
                ('motif', models.CharField(blank=True, max_length=40, verbose_name='motif')),
                ('niveau_accorde', models.CharField(blank=True, max_length=20, verbose_name='niveau accordé')),
                ('decide_par', models.CharField(max_length=120, verbose_name='décidé par')),
                ('decide_le', models.DateTimeField(auto_now_add=True, verbose_name='décidé le')),
                ('canal', models.CharField(choices=[('courriel', 'Courriel'), ('appel', 'Appel téléphonique')], max_length=20, verbose_name="canal d'annonce")),
                ('notifie_le', models.DateTimeField(blank=True, null=True, verbose_name='annoncé le')),
                ('groupeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_kyc', to='comptes.groupeur', verbose_name='groupeur')),
            ],
            options={
                'verbose_name': 'décision KYC',
                'verbose_name_plural': 'décisions KYC',
                'ordering': ('-decide_le',),
            },
        ),
        migrations.CreateModel(
            name='PieceKyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('piece-recto', "Pièce d'identité — recto"), ('piece-verso', "Pièce d'identité — verso"), ('selfie', 'Selfie tenant la pièce'), ('etal', "Lieu d'activité"), ('justificatif', "Justificatif d'activité")], max_length=20, verbose_name='nature')),
                ('reference', models.CharField(max_length=200, verbose_name='référence de stockage')),
                ('depose_le', models.DateTimeField(auto_now_add=True, verbose_name='déposée le')),
                ('groupeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='comptes.groupeur', verbose_name='groupeur')),
            ],
            options={
                'verbose_name': 'pièce KYC',
                'verbose_name_plural': 'pièces KYC',
                'ordering': ('groupeur', 'nature'),
                'constraints': [models.UniqueConstraint(fields=('groupeur', 'nature'), name='une_piece_par_nature')],
            },
        ),
    ]
