# Generated by Django 5.2.18 on 2026-10-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_groupeur_courriel_decisionkyc_piecekyc'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(db_index=True, max_length=20, verbose_name='téléphone')),
                ('code_hache', models.CharField(max_length=128, verbose_name='code haché')),
                ('essais', models.PositiveSmallIntegerField(default=0, verbose_name='essais')),
                ('consomme', models.BooleanField(default=False, verbose_name='consommé')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
            ],
            options={
                'verbose_name': 'code de connexion',
                'verbose_name_plural': 'codes de connexion',
                'ordering': ('-cree_le',),
            },
        ),
        migrations.AddField(
            model_name='acheteur',
            name='quartier',
            field=models.CharField(blank=True, max_length=40, verbose_name='quartier'),
        ),
        migrations.AddField(
            model_name='acheteur',
            name='repere',
            field=models.CharField(blank=True, max_length=200, verbose_name='repère'),
        ),
        migrations.CreateModel(
            name='SessionAcheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='jeton')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='ouverte le')),
                ('expire_le', models.DateTimeField(verbose_name='expire le')),
                ('dernier_usage', models.DateTimeField(auto_now_add=True, verbose_name='dernier usage')),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='comptes.acheteur', verbose_name='acheteur')),
            ],
            options={
                'verbose_name': 'session acheteur',
                'verbose_name_plural': 'sessions acheteurs',
                'ordering': ('-dernier_usage',),
            },
        ),
    ]
