# Generated by Django 5.2.18 on 2026-10-08 10:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=160, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('contenu_part', models.CharField(max_length=240, verbose_name='ce que contient une part')),
                ('categorie', models.CharField(choices=[('alimentaire', 'Alimentaire'), ('vetements', 'Vêtements'), ('chaussures', 'Chaussures'), ('hygiene', 'Hygiène'), ('maison', 'Maison'), ('electronique', 'Électronique')], max_length=20, verbose_name='catégorie')),
                ('prix_part', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name="prix d'une part")),
                ('media', models.URLField(blank=True, verbose_name='média')),
                ('media_alt', models.CharField(blank=True, max_length=200, verbose_name='description du média')),
                ('date_fin', models.DateTimeField(verbose_name='date de clôture')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('a-decider', 'À décider'), ('en-cours', 'Commande en cours'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='ouverte', max_length=20, verbose_name='statut')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('groupeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='comptes.groupeur', verbose_name='groupeur')),
            ],
            options={
                'verbose_name': 'campagne',
                'verbose_name_plural': 'campagnes',
                'ordering': ('date_fin',),
                'indexes': [models.Index(fields=['statut', 'date_fin'], name='catalogue_c_statut_ebc339_idx')],
            },
        ),
    ]
