# Generated by Django 5.2.18 on 2026-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='caracteristiques',
            field=models.JSONField(blank=True, default=list, verbose_name='caractéristiques'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='point_remise',
            field=models.CharField(blank=True, max_length=200, verbose_name='point de remise'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='quartier_remise',
            field=models.CharField(blank=True, max_length=40, verbose_name='quartier de remise'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='remise_le',
            field=models.DateField(blank=True, null=True, verbose_name='remise prévue le'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='variante_libelle',
            field=models.CharField(blank=True, max_length=60, verbose_name='libellé de la variante'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='variante_options',
            field=models.JSONField(blank=True, default=list, verbose_name='options de la variante'),
        ),
    ]
